### PR TITLE
Fix JSON boolean handling for jessie and trusty #309

### PR DESCRIPTION
**Pull request by vvidic**
Toolkit fails to load test configuration from disk.

### CODE REVIEW

**Comment by vvidic** [comment]
Andy, can you check this fix for the toolkit issue with loading test configuration?

**Comment by tonin** [comment]
@vvidic do we still need this PR OR has this been solved with the new include trick?

**Comment by vvidic** [comment]
On Sun, Jun 10, 2018 at 11:14:52PM -0700, Antoine Delvaux wrote:
> @vvidic do we still need this PR OR has this been solved with the new include trick?

Seems that test configuration is still empty.  Maybe we need to add an
include in one more place...

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
On Sun, Jun 10, 2018 at 11:14:52PM -0700, Antoine Delvaux wrote:
> @vvidic do we still need this PR OR has this been solved with the new include trick?

Adding use to regular_testing.cgi also fixes the problem, guess we
should use that?

  use perfSONAR_PS::Client::Utils;

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Pull request closed without merging**
