### PR TITLE
Fix Virtual Machine detection for Xen

### PR DESCRIPTION
**Pull request by vvidic**
Debian Stretch VM reported as not virtual.

### CODE REVIEW

**Comment by arlake228** [comment]
I don't have a way to test so going to trust you on this one. Merging into 4.2.0.

**Comment by vvidic** [comment]
Not sure why I don't see this change in the nightly packages yet?

**Comment by arlake228** [comment]
I believe this has only been merged into 4.2.0 which we have not built for nightly yet. We need to reorganize our testbed to better handle the parallel versions we have going. I have some thoughts on this, just have not had time to propose and implement yet.

**Comment by vvidic** [comment]
No problem, just as long it is not lost :)

-- 
Valentin

**Pull request merged**
